[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirección necesaria para React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200