import type { Property } from "./types"

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Villa Mediterránea de Lujo",
    description:
      "Impresionante villa frente al mar con piscina infinita y vistas panorámicas al mar. Cuenta con 5 habitaciones, acceso privado a la playa y comodidades de última generación.",
    images: ["/luxury-mediterranean-villa-sunset-pool.jpg", "/luxury-villa-interior-gold-accents.jpg"],
    bedrooms: 5,
    bathrooms: 4,
    parking: 3,
    price: 2500000,
    location: "Marbella, España",
    province: "Málaga",
    propertyType: "casa",
    surfaceArea: 450,
    condition: "nuevo",
    availability: "venta",
    amenities: {
      garage: true,
      storage: true,
      garden: true,
      pool: true,
      terrace: true,
    },
    featured: true,
    type: "vip",
    visits: 1250,
    publishedDate: "2025-01-15",
  },
  {
    id: "2",
    title: "Ático Centro Ciudad",
    description:
      "Elegante ático en el corazón de la ciudad con impresionantes vistas al horizonte. Diseño moderno con acabados premium en todo el espacio.",
    images: ["/elegant-penthouse-city-skyline-view.jpg", "/modern-penthouse-interior.png"],
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    price: 1800000,
    location: "Madrid, España",
    province: "Madrid",
    propertyType: "atico",
    surfaceArea: 280,
    condition: "buen-estado",
    availability: "venta",
    amenities: {
      garage: true,
      storage: false,
      garden: false,
      pool: false,
      terrace: true,
    },
    featured: true,
    type: "vip",
    visits: 980,
    publishedDate: "2025-01-10",
  },
  {
    id: "3",
    title: "Paraíso Frente al Mar",
    description:
      "Propiedad exclusiva frente al mar con acceso directo al océano. Perfecta para aquellos que buscan tranquilidad y lujo junto al mar.",
    images: ["/beachfront-luxury-property-ocean-view.jpg", "/placeholder.svg?height=400&width=600"],
    bedrooms: 4,
    bathrooms: 3,
    parking: 2,
    price: 1950000,
    location: "Costa del Sol, España",
    province: "Málaga",
    propertyType: "casa",
    surfaceArea: 380,
    condition: "obra-nueva",
    availability: "venta",
    amenities: {
      garage: true,
      storage: true,
      garden: true,
      pool: true,
      terrace: true,
    },
    featured: true,
    type: "basic",
    visits: 875,
    publishedDate: "2025-01-20",
  },
  {
    id: "4",
    title: "Refugio Chalet de Montaña",
    description:
      "Lujoso chalet de montaña con impresionantes vistas alpinas. Ideal para entusiastas de los deportes de invierno y amantes de la naturaleza.",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    bedrooms: 4,
    bathrooms: 3,
    parking: 2,
    price: 1650000,
    location: "Sierra Nevada, España",
    province: "Granada",
    propertyType: "casa",
    surfaceArea: 320,
    condition: "buen-estado",
    availability: "alquiler",
    amenities: {
      garage: true,
      storage: true,
      garden: false,
      pool: false,
      terrace: true,
    },
    featured: false,
    type: "basic",
    visits: 654,
    publishedDate: "2024-12-28",
  },
  {
    id: "5",
    title: "Loft Urbano Moderno",
    description:
      "Apartamento tipo loft contemporáneo con detalles dorados e interiores de diseño. Ubicado en el barrio más exclusivo.",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    price: 950000,
    location: "Barcelona, España",
    province: "Barcelona",
    propertyType: "piso",
    surfaceArea: 180,
    condition: "nuevo",
    availability: "venta",
    amenities: {
      garage: true,
      storage: false,
      garden: false,
      pool: false,
      terrace: false,
    },
    featured: false,
    type: "basic",
    visits: 532,
    publishedDate: "2025-01-05",
  },
  {
    id: "6",
    title: "Villa Exclusiva con Campo de Golf",
    description:
      "Magnífica villa con vistas al campo de golf de campeonato. Ubicación premium con acceso al club de campo.",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    bedrooms: 6,
    bathrooms: 5,
    parking: 4,
    price: 3200000,
    location: "Marbella, España",
    province: "Málaga",
    propertyType: "casa",
    surfaceArea: 580,
    condition: "nuevo",
    availability: "venta",
    amenities: {
      garage: true,
      storage: true,
      garden: true,
      pool: true,
      terrace: true,
    },
    featured: false,
    type: "vip",
    visits: 423,
    publishedDate: "2024-12-20",
  },
  {
    id: "7",
    title: "Propiedad Costera Moderna",
    description: "Obra maestra arquitectónica contemporánea con espacios de vida interiores y exteriores sin costuras.",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    bedrooms: 5,
    bathrooms: 4,
    parking: 3,
    price: 2800000,
    location: "Valencia, España",
    province: "Valencia",
    propertyType: "casa",
    surfaceArea: 420,
    condition: "obra-nueva",
    availability: "venta",
    amenities: {
      garage: true,
      storage: true,
      garden: true,
      pool: true,
      terrace: true,
    },
    featured: false,
    type: "vip",
    visits: 389,
    publishedDate: "2025-01-12",
  },
  {
    id: "8",
    title: "Palacio Histórico Renovado",
    description: "Hermosa propiedad histórica restaurada que combina elegancia clásica con lujo moderno.",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    bedrooms: 7,
    bathrooms: 6,
    parking: 5,
    price: 4500000,
    location: "Sevilla, España",
    province: "Sevilla",
    propertyType: "casa",
    surfaceArea: 680,
    condition: "a-reformar",
    availability: "venta",
    amenities: {
      garage: true,
      storage: true,
      garden: true,
      pool: false,
      terrace: true,
    },
    featured: false,
    type: "vip",
    visits: 367,
    publishedDate: "2024-12-15",
  },
  {
    id: "9",
    title: "Villa Minimalista de Diseño",
    description: "Diseño minimalista galardonado con tecnología de hogar inteligente de vanguardia.",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    bedrooms: 4,
    bathrooms: 4,
    parking: 3,
    price: 2100000,
    location: "Ibiza, España",
    province: "Islas Baleares",
    propertyType: "casa",
    surfaceArea: 350,
    condition: "nuevo",
    availability: "alquiler-opcion-compra",
    amenities: {
      garage: true,
      storage: false,
      garden: true,
      pool: true,
      terrace: true,
    },
    featured: false,
    type: "basic",
    visits: 298,
    publishedDate: "2025-01-08",
  },
  {
    id: "10",
    title: "Finca en el Campo",
    description: "Extensa finca rural con viñedos y olivares. Tu santuario privado.",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    bedrooms: 8,
    bathrooms: 7,
    parking: 6,
    price: 5200000,
    location: "Mallorca, España",
    province: "Islas Baleares",
    propertyType: "finca",
    surfaceArea: 850,
    condition: "buen-estado",
    availability: "venta",
    amenities: {
      garage: true,
      storage: true,
      garden: true,
      pool: true,
      terrace: true,
    },
    featured: false,
    type: "vip",
    visits: 276,
    publishedDate: "2024-12-10",
  },
]
